.catalog:
  name: "Vault Server"
  version: "0.4-pk4media1"
  description: |
    Vault Server.
  uuid: vault-server-0
  minimum_rancher_version: v0.56.0
  questions:
    - variable: server_count
      description: "Number of servers to bootstrap"
      label: "Server Bootstrap Count"
      type: "int"
      required: true
      default: 3
vault:
  scale: ${server_count}
